version: '3.8'

networks:
  appnetwork:

services:
  csvserver:
    image: infracloudio/csvserver:latest
    container_name: csvserver
    ports:
      - "9393:9300"
    env_file:
      - ./csvserver.env
    volumes:
      - ./inputFile:/csvserver/inputdata
    networks:
      - appnetwork

  prometheus:
    image: prom/prometheus:v2.45.2
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - appnetwork
